name: fh_sdk
description: Unofficial flutter plugin for Red Hat Mobile
version: 0.6.6
author: Carlos Vicens <carlos.vicens.alonso@gmail.com>
homepage: https://github.com/cvicens/flutter-fh/tree/master/

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.redhat.fhsdk
    pluginClass: FhSdkPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"